conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_page, AboutView


app_name = 'home'
urlpatterns = [
    path('', home_page, name='home-page'),
    path('about/', AboutView.as_view(), name='about'),
    ]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView
from home.views import home_page


app_name = 'users'
urlpatterns = [
    path('home/', home_page, name='home-page'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update-profile/', ProfileUpdateView.as_view(), name='update-profile'),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.


class CustomUser(AbstractUser):
    image = models.ImageField(upload_to='users_image/', blank=True, null=True, default='default_img/user_img.png')

    class Meta:
        db_table = 'custom_user'

    def __str__(self):
        return self.username

users/forms.py
from django import forms
from .models import CustomUser


class CustomUserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = CustomUser
        fields = ['first_name', 'last_name', 'email', 'username', 'password']

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password'])
        if commit:
            user.save()
        return user


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = CustomUser
        fields = ('image', 'first_name', 'last_name', 'email', 'username')

users/views.py
from django.shortcuts import render, redirect
from .forms import CustomUserForm, ProfileUpdateForm
from django.views import View
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login, logout
# Create your views here.


class RegisterView(View):
    def get(self, request):
        create_form = CustomUserForm()
        context = {
            'form': create_form
        }
        return render(request, 'register.html', context=context)

    def post(self, request):
        create_form = CustomUserForm(data=request.POST, files=request.FILES)
        if create_form.is_valid():
            create_form.save()
            return redirect('users:login')
        else:
            context = {
                'form': create_form
            }
            return render(request, 'register.html', context=context)


class LoginView(View):
    def get(self, request):
        create_form = AuthenticationForm()
        context = {
            'form': create_form
        }
        return render(request, 'login.html', context=context)

    def post(self, request):
        login_form = AuthenticationForm(data=request.POST)
        if login_form.is_valid():
            user = login_form.get_user()
            login(request, user)
            return redirect('home:home-page')
        else:
            context = {
                'form': login_form
            }
            return render(request, 'login.html', context=context)


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('home:home-page')


class ProfileView(View):
    def get(self, request):
        context = {
            'user': request.user
        }
        return render(request, 'profile.html', context=context)


class ProfileUpdateView(View):
    def get(self, request):
        update_form = ProfileUpdateForm(instance=request.user)
        context = {
            'form': update_form
        }
        return render(request, 'profile_update.html', context=context)

    def post(self, request):
        update_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user)
        if update_form.is_valid():
            update_form.save()
            return redirect('users:profile')
        else:
            context = {
                'form': update_form
            }
            return render(request, 'profile_update.html', context=context)

users/templates/login.html
{% load static %}
<link rel="stylesheet" href="{% static 'css/for_login.css' %}">
<title>Login</title>

<header>
  <a href="{% url 'home:home-page' %}">iCap</a>
</header>

<body>
  <h1>Login Page</h1>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
  </form>
</body>

users/templates/profile.html
<title>Profile</title>

{% load static %}
<link rel="stylesheet" href="{% static 'css/for_profile.css' %}">
<header>
  <a href="{% url 'home:home-page' %}">iCap</a><br><br>
  <a href="{% url 'home:about' %}">About</a> |
  <a href="{% url 'users:logout' %}">logout</a>
</header>
<body>
  <h1>Profile</h1>
  <img alt="user-image" style="border-radius: 55px" src="{{ user.image.url }} " height="100px"><br>
  <h3>Username: {{ user.username }}</h3>
  <h3>First name: {{ user.first_name }}</h3>
  <h3>Last name: {{ user.last_name }}</h3>
  <h3>Email: {{ user.email }}</h3>

  <a href="{% url 'users:update-profile' %}"><button>Edit profile</button></a>
</body>

users/templates/profile_update.html
<title>UpdateProfile</title>

{% load static %}
<link rel="stylesheet" href="{% static 'css/for_proflle_update.css' %}">
<header>
  <a href="{% url 'home:home-page' %}">iCap</a>
</header>

<body>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update Profile">
  </form>
</body>

users/templates/register.html
<title>Register</title>
{% load static %}
<link rel="stylesheet" href="{% static 'css/for_register.css' %}">
<header>
  <a href="{% url 'home:home-page' %}">iCap</a>
</header>

<body>
  <h1>Register Page</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">submit</button>
  </form>
</body>