conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home/urls.py
from django.urls import path
from .views import home_page, AboutView


app_name = 'home'
urlpatterns = [
    path('', home_page, name='home-page'),
    path('about/', AboutView.as_view(), name='about'),
    ]

products/urls.py
from django.urls import path
from .views import CategoryListView, MaleListView, FemaleListView, MaleDetailView, CapCreateView, BookDeleteView, \
    AddReview, SaveCapView

app_name = 'products'
urlpatterns = [
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('products/<int:pk>/', MaleListView.as_view(), name='male-list'),
    path('products/<int:pk>/', FemaleListView.as_view(), name='female-list'),
    path('products/detail/<int:pk>/', MaleDetailView.as_view(), name='detail'),
    path('products/create', CapCreateView.as_view(), name='create-cap'),
    path('delete/<int:pk>/', BookDeleteView.as_view(), name='delete-cap'),
    path('add-review/<int:pk>', AddReview.as_view(), name='add-review'),
    path('save/<int:pk>/', SaveCapView.as_view(), name='save-cap'),
]

users/urls.py
from django.urls import path
from .views import RegisterView, LoginView, LogoutView, ProfileView, ProfileUpdateView
from home.views import home_page


app_name = 'users'
urlpatterns = [
    path('home/', home_page, name='home-page'),
    path('register/', RegisterView.as_view(), name='register'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('update-profile/', ProfileUpdateView.as_view(), name='update-profile'),
]

home/models.py
from django.db import models

# Create your models here.


class About(models.Model):
    image = models.ImageField(upload_to='about/', blank=True, null=True, default='default_img/user_img.png')
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    title = models.TextField()

    class Meta:
        db_table = 'about_us'

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

home/forms.py
from django import forms
from .models import About


class AboutViewForm(forms.ModelForm):
    class Meta:
        model = About
        fields = ['image', 'first_name', 'last_name', 'title']

home/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import About
from django.views import View
from .forms import AboutViewForm
# Create your views here.


def home_page(request):
    return render(request, 'home.html')


class AboutView(View):
    def get(self, request):
        about1 = About.objects.all()
        context = {
            'about_us': about1
        }
        return render(request, 'about.html', context=context)

home/templates/about.html
{% extends 'base.html' %}
{% load static %}
<link rel="stylesheet" href="{% static 'css/about.css' %}">
{% block content %}
<div class="container">
    <h1>About Us</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for about in about_us %}
            {% if about.pk == 1 %}
                <img src="{{ about.image.url }}" height="200px" alt="CEO Image"><br><br>
                <h2>My name is {{ about.first_name }} {{ about.last_name }}. I'm the CEO of iCap online shop.</h2>
                <h3>{{ about.title }}</h3>
            {% endif %}
        {% endfor %}
    </form>
</div>
{% endblock content %}

home/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>iCap</title>
    <link rel="stylesheet" href="{% static 'css/for_base.css' %}">
</head>
<body>
<header>
    {% if user.is_authenticated %}
        <h1>Welcome {{ user.username }}!</h1>
        <nav>
            <h1><a href="{% url 'home:home-page' %}">iCap</a></h1>
            <h3><a href="{% url 'products:category-list' %}">Categories</a></h3>
            <h3><a href="#">Saved</a></h3>
            <h3><a href="{% url 'users:profile' %}">Profile</a></h3>
            <h3><a href="{% url 'home:about' %}">About</a></h3>
            <h3><a href="{% url 'users:logout' %}">Logout</a></h3>
        </nav>
    {% else %}
        <nav>
            <h1><a href="{% url 'home:home-page' %}">iCap</a></h1>
            <h3><a href="{% url 'products:category-list' %}">Categories</a></h3>
            <h3><a href="{% url 'users:register' %}">Register</a></h3>
            <h3><a href="{% url 'users:login' %}">Login</a></h3>
            <h3><a href="{% url 'home:about' %}">About</a></h3>
        </nav>
    {% endif %}
</header>
<br><br><br>
<div>
    {% block content %}
    {% endblock content %}
</div>
</body>
</html>

home/templates/home.html
{% extends 'base.html' %}

{% block content %}
<body>
    <h1>
        Cool Caps. Cool Look
    </h1>
</body>
{% endblock content %}