conf/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('users/', include('users.urls')),
    path('products/', include('products.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import CategoryListView, MaleListView, FemaleListView, MaleDetailView, CapCreateView, BookDeleteView, \
    AddReview, SaveCapView

app_name = 'products'
urlpatterns = [
    path('category-list/', CategoryListView.as_view(), name='category-list'),
    path('products/<int:pk>/', MaleListView.as_view(), name='male-list'),
    path('products/<int:pk>/', FemaleListView.as_view(), name='female-list'),
    path('products/detail/<int:pk>/', MaleDetailView.as_view(), name='detail'),
    path('products/create', CapCreateView.as_view(), name='create-cap'),
    path('delete/<int:pk>/', BookDeleteView.as_view(), name='delete-cap'),
    path('add-review/<int:pk>', AddReview.as_view(), name='add-review'),
    path('save/<int:pk>/', SaveCapView.as_view(), name='save-cap'),
]

products/models.py
from django.db import models
from django.core.validators import MinValueValidator, MaxValueValidator
from users.models import CustomUser
# Create your models here.


class Categories(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        db_table = 'categories'

    def __str__(self):
        return self.name


class Sizes(models.Model):
    size = models.CharField(max_length=6)

    class Meta:
        db_table = 'sizes'

    def __str__(self):
        return self.size


class Colors(models.Model):
    color = models.CharField(max_length=20)

    class Meta:
        db_table = 'colors'

    def __str__(self):
        return self.color


class Caps(models.Model):
    image = models.ImageField(upload_to='caps/')
    category_name = models.ForeignKey(Categories, on_delete=models.DO_NOTHING)
    name = models.CharField(max_length=100)
    make = models.CharField(max_length=100)
    color = models.ForeignKey(Colors, on_delete=models.DO_NOTHING)
    price = models.IntegerField()

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)

    class Meta:
        db_table = 'caps'

    def __str(self):
        return f"{self.category_name.name} {self.name}"


class Review(models.Model):
    comment = models.CharField(max_length=200)
    star_given = models.IntegerField(
        default=0,
        validators=[
            MaxValueValidator(5),
            MinValueValidator(0)
        ]
     )
    book = models.ForeignKey(Caps, on_delete=models.CASCADE)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    class Meta:
        db_table = 'review'

    def __str__(self):
        return f'{self.star_given} - {self.book.name} - {self.user.username}'

products/forms.py
from django.forms import ModelForm
from django import forms
from .models import Review


class AddReviewForm(ModelForm):
    star_given = forms.IntegerField(max_value=5, min_value=0)

    class Meta:
        model = Review
        fields = ['comment', 'star_given']

products/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import CreateView, DeleteView
from .models import Categories, Caps, Review
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import AddReviewForm
# Create your views here.


class CategoryListView(View):
    def get(self, request):
        categories = Categories.objects.all()
        context = {
            'form': categories
        }
        return render(request, 'category_list.html', context=context)


class MaleListView(View):
    def get(self, request, pk):
        caps = Caps.objects.filter(category_name=pk).order_by('-id')
        context = {
            'male_caps': caps
        }
        return render(request, 'male_list.html', context=context)


class MaleDetailView(View):
    def get(self, request, pk):
        caps = Caps.objects.get(pk=pk)
        context = {
            'cap': caps,
        }
        return render(request, 'detail.html', context=context)


class FemaleListView(View):
    def get(self, request, pk):
        caps = Caps.objects.filter(category_name=pk).order_by('-id')
        context = {
            'female_caps': caps
        }
        return render(request, 'female_list.html', context=context)


class CapCreateView(CreateView):
    model = Caps
    template_name = 'create_caps.html'
    fields = '__all__'
    success_url = reverse_lazy('products:category-list')


class BookDeleteView(DeleteView):
    model = Caps
    template_name = 'delete_caps.html'
    success_url = reverse_lazy('products:category-list')


class AddReview(LoginRequiredMixin, View):
    def get(self, request, pk):
        caps = Caps.objects.get(pk=pk)
        add_review_form = AddReviewForm()
        context = {
            'caps': caps,
            'add_review_form': add_review_form
        }
        return render(request, 'add_review.html', context=context)

    def post(self, request, pk):
        caps = Caps.objects.get(pk=pk)
        add_review_form = AddReviewForm(request.POST)
        if add_review_form.is_valid():
            # Ensure user is authenticated
            if request.user.is_authenticated:
                review = Review.objects.create(
                    comment=add_review_form.cleaned_data['comment'],
                    book=caps,
                    user=request.user,
                    star_given=add_review_form.cleaned_data['star_given']
                )
                review.save()
                return redirect('products:category-list')
            else:
                # Handle the case where user is not authenticated
                return redirect('login')  # Redirect to login page
        else:
            context = {
                'caps': caps,
                'add_review_form': add_review_form
            }
            return render(request, 'add_review.html', context=context)


class SaveCapView(View):
    def get(self, request, pk):
        caps = Caps.objects.get(pk=pk)
        context = {
            'caps': caps
        }
        return render(request, 'save_cap.html', context=context)

products/templates/add_review.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
{% extends 'base.html'%}
<body>
{% block content %}
<h1>{{ caps.name }}</h1>
<form method="post" >
    {% csrf_token %}
    {{ add_review_form.as_p }}
    <input type="submit" value="Add Review">
</form>

{% endblock content%}
</body>
</html>

products/templates/category_list.html
<title>Category</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <body>
        {% for i in form %}
            {% if i.id == 1 %}
            <a href="{% url 'products:male-list' i.pk %}">{{ i.name }}</a><br><br>
            {% elif i.id == 2 %}
            <a href="{% url 'products:female-list' i.pk %}">{{ i.name }}</a>
            {% else %}
            <a href="#">{{ i.name }}</a><br>
            {% endif %}
        {% endfor %}
    </body>
{% endblock content %}

products/templates/create_caps.html
{% extends 'base.html' %}
{% block content %}
<h1>Create Cap</h1>
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Save">
  </form>
{% endblock content %}

products/templates/delete_caps.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>DeleteCaps</title>
</head>
<body><br><br><br>
  <form method="post">
    {% csrf_token %}
    <input type="submit" value="Confirm"><br><br>
  </form>
  <a href="{% url 'products:category-list' %}"><button>No</button></a>
</body>
</html>

products/templates/detail.html
<title>Products</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <body>
        <img src="{{ cap.image.url }}" height="300px"><br><br>
        {% if user.is_staff %}
            <a href="{% url 'products:delete-cap' cap.pk %}">Delete</a><br>
        {% endif %}
        <a href="{% url 'products:save-cap' cap.pk %}"><button>Save</button></a>
        <h3>Name: {{ cap.name }}</h3>
        <h4>Category: {{ cap.category_name }}</h4>
        <h4>Make: {{ cap.make }}</h4>
        <h4>Color: {{ cap.color }}</h4>
        <h4>Price: {{ cap.price }}$</h4>
        <a href="{% url 'products:add-review' cap.pk %}">Add comment</a>
    </body>
{% endblock content %}

products/templates/female_list.html
<title>FemaleCategory</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/female.css' %}">
    <body>
        {% for i in caps %}
                <a href="{% url 'products:detail' i.pk %}"><img src="{{ i.image.url }}" height="200px"></a> <br><br>
                <h4>Make: {{ i.make}}</h4>
                <h4>Price: {{ i.price }}$</h4>
        {% endfor %}
    </body>
{% endblock content %}

products/templates/male_list.html
<title>MaleCategory</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/female.css' %}">
    <a href="{% url 'products:create-cap' %}"><button>Add Cap</button></a>
    <body><br><br><br>
        {% for i in male_caps %}
                <a href="{% url 'products:detail' i.pk %}"><img src="{{ i.image.url }}" height="200px"></a> <br><br>
                <h4>Make: {{ i.make}}</h4>
                <h4>Price: {{ i.price }}$</h4>
        {% endfor %}
    </body>
{% endblock content %}

products/templates/save_cap.html
<title>Saved</title>
{% extends 'base.html' %}
{% load static %}
{% block content %}
<link rel="stylesheet" href="{% static 'css/detail.css' %}">
    <body>
        <img src="{{ caps.image.url }}" height="300px"><br><br>
        {% if user.is_staff %}
            <a href="{% url 'products:delete-cap' caps.pk %}">Delete</a><br>
        {% endif %}
        <h3>Name: {{ caps.name }}</h3>
        <h4>Category: {{ caps.category_name }}</h4>
        <h4>Make: {{ caps.make }}</h4>
        <h4>Color: {{ caps.color }}</h4>
        <h4>Price: {{ caps.price }}$</h4>
        <a href="{% url 'products:add-review' caps.pk %}">Add comment</a>
    </body>
{% endblock content %}